/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kalkulator;

/**
 *
 * @author user
 */
public class Kalkulator extends javax.swing.JFrame {

   private String operator ="";
   private String parameter="0";
   private String outDisplay2="";
   private String reset ="";
   private double numd1,numd2;
   private int sum;
    public Kalkulator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        display = new javax.swing.JTextField();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btnMin = new javax.swing.JButton();
        btnDot = new javax.swing.JButton();
        btnPlus = new javax.swing.JButton();
        btnMinus = new javax.swing.JButton();
        btnMulti = new javax.swing.JButton();
        btnDiv = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnEqual = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        display2 = new javax.swing.JLabel();
        btnDel = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));

        display.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        btn1.setText("1");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn2.setText("2");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn3.setText("3");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btn4.setText("4");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        btn5.setText("5");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        btn6.setText("6");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });

        btn7.setText("7");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });

        btn8.setText("8");
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });

        btn9.setText("9");
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });

        btn0.setText("0");
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });

        btnMin.setText("+/-");
        btnMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinActionPerformed(evt);
            }
        });

        btnDot.setText(".");
        btnDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDotActionPerformed(evt);
            }
        });

        btnPlus.setText("+");
        btnPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlusActionPerformed(evt);
            }
        });

        btnMinus.setText("-");
        btnMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinusActionPerformed(evt);
            }
        });

        btnMulti.setText("x");
        btnMulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiActionPerformed(evt);
            }
        });

        btnDiv.setText("/");
        btnDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivActionPerformed(evt);
            }
        });

        btnClear.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnClear.setText("C");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnEqual.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnEqual.setText("=");
        btnEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEqualActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(153, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Kalkulator");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setOpaque(true);

        display2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        display2.setText(" ");

        btnDel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnDel.setText("Del");
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(display2, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(display, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(btnMin, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnMulti, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(btnEqual, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnDot, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnDel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(display2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(display, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMulti, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMin, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDot, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnEqual, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnDel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        display.setEditable(false);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        String getDisplay = display.getText();
         if(getDisplay.equals("0")){
          display.setText("1");
      }
         else if(reset.equals("y")){
             display.setText("");
             getDisplay = display.getText();
             String setDisplay = getDisplay+"1";
             display.setText(setDisplay);
             reset="n";
         }
      else {
        String setDisplay = getDisplay+"1";
        display.setText(setDisplay);
      }
       
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        String getDisplay = display.getText();
         if(getDisplay.equals("0")){
          display.setText("2");
      } 
         else if(reset.equals("y")){
             display.setText("");
             getDisplay = display.getText();
             String setDisplay = getDisplay+"2";
             display.setText(setDisplay);
             reset="n";
         }
      else {
        String setDisplay = getDisplay+"2";
        display.setText(setDisplay);
      }        
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        String getDisplay = display.getText();
         if(getDisplay.equals("0")){
          display.setText("3");
      }
          else if(reset.equals("y")){
             display.setText("");
             getDisplay = display.getText();
             String setDisplay = getDisplay+"3";
             display.setText(setDisplay);
             reset="n";
         }
      else {
        String setDisplay = getDisplay+"3";
        display.setText(setDisplay);
      }
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
       String getDisplay = display.getText();
         if(getDisplay.equals("0")){
          display.setText("4");
      }
          else if(reset.equals("y")){
             display.setText("");
             getDisplay = display.getText();
             String setDisplay = getDisplay+"4";
             display.setText(setDisplay);
             reset="n";
         }
      else {
        String setDisplay = getDisplay+"4";
        display.setText(setDisplay);
      }
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
     String getDisplay = display.getText();
         if(getDisplay.equals("0")){
          display.setText("5");
      }
          else if(reset.equals("y")){
             display.setText("");
             getDisplay = display.getText();
             String setDisplay = getDisplay+"5";
             display.setText(setDisplay);
             reset="n";
         }
      else {
        String setDisplay = getDisplay+"5";
        display.setText(setDisplay);
      }
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
       String getDisplay = display.getText();
         if(getDisplay.equals("0")){
          display.setText("6");
      }
          else if(reset.equals("y")){
             display.setText("");
             getDisplay = display.getText();
             String setDisplay = getDisplay+"6";
             display.setText(setDisplay);
             reset="n";
         }
      else {
        String setDisplay = getDisplay+"6";
        display.setText(setDisplay);
      }
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
      String getDisplay = display.getText(); 
      if(getDisplay.equals("0")){
          display.setText("7");
      }
       else if(reset.equals("y")){
             display.setText("");
             getDisplay = display.getText();
             String setDisplay = getDisplay+"7";
             display.setText(setDisplay);
             reset="n";
         }
      else {
        String setDisplay = getDisplay+"7";
        display.setText(setDisplay);
      }
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
    String getDisplay = display.getText();
    if(getDisplay.equals("0")){
          display.setText("8");
      }
     else if(reset.equals("y")){
             display.setText("");
             getDisplay = display.getText();
             String setDisplay = getDisplay+"8";
             display.setText(setDisplay);
             reset="n";
         }
      else {
        String setDisplay = getDisplay+"8";
        display.setText(setDisplay);
      }
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
      String getDisplay = display.getText();
       if(getDisplay.equals("0")){
          display.setText("9");
      }
        else if(reset.equals("y")){
             display.setText("");
             getDisplay = display.getText();
             String setDisplay = getDisplay+"9";
             display.setText(setDisplay);
             reset="n";
         }
      else {
        String setDisplay = getDisplay+"9";
        display.setText(setDisplay);
      }
    }//GEN-LAST:event_btn9ActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        display.setText("");
        display2.setText("");
        parameter = "0";
        outDisplay2 = "";
        reset = "";
        numd1 = 0;
        numd2 = 0;
    }//GEN-LAST:event_btnClearActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
      String getDisplay = display.getText();
      if(getDisplay.equals("0")){
          display.setText("0");
      }
       else if(reset.equals("y")){
             display.setText("");
             getDisplay = display.getText();
             String setDisplay = getDisplay+"0";
             display.setText(setDisplay);
             reset="n";
         }
      else {
        String setDisplay = getDisplay+"0";
        display.setText(setDisplay);
      }
    }//GEN-LAST:event_btn0ActionPerformed

    private void btnDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDotActionPerformed
        String getDisplay = display.getText();
        if(getDisplay.equals("")){
            display.setText("");
        }
        else if (getDisplay.contains(".")){
        display.setText(getDisplay);
        }
        else{
        String setDisplay = getDisplay+".";
        display.setText(setDisplay);
        }
    }//GEN-LAST:event_btnDotActionPerformed

    private void btnMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinActionPerformed
        try{
        int num1 = Integer.valueOf(display.getText()) ;
        num1 = num1 * (-1);
        String setDisplay = String.valueOf(num1);
        display.setText(setDisplay);
        }
        catch (NumberFormatException e){
        double num1 = Double.valueOf(display.getText()) ;
        num1 = num1 * (-1);
        String setDisplay = String.valueOf(num1);
        display.setText(setDisplay);
        }
    }//GEN-LAST:event_btnMinActionPerformed

    private void btnPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlusActionPerformed
        String getDisplay = display.getText();
        if(getDisplay.equals("")){
            display.setText("");
        }
        else if (parameter.equals("0")){
            parameter = "1";
            display.setText("");
            String setDisplay2 = getDisplay + " + ";
            outDisplay2 = outDisplay2+setDisplay2;
            display2.setText(outDisplay2);
            numd1= Double.valueOf(getDisplay);
            operator ="+";
        }
        else if (parameter.equals("1")){
            reset = "y";
            parameter = "2";
            numd2 = Double.valueOf(getDisplay);
            switch (operator) {
                case "+":
                    numd1 = numd1+numd2;
                    break;
                case "-":
                    numd1 = numd1-numd2;
                    break;
                case "x":
                    numd1 = numd1*numd2;
                    break;
                case "/":
                    numd1 = numd1/numd2;
                    break;
                default:
                    break;
            }
            if (numd1 % 1 == 0){
                sum = (int)numd1;
                String setDisplay = String.valueOf(sum);
                display.setText(setDisplay); 
            }
            else{
                String setDisplay = String.valueOf(numd1);
            display.setText(setDisplay);
            }
            String setDisplay2 = getDisplay + " + ";
            outDisplay2 = outDisplay2+setDisplay2;
            display2.setText(outDisplay2);
            operator ="+";
        }
        else if (parameter.equals("2")){
            if(reset.equals("n")){
            reset = "y";
            numd2 = Double.valueOf(display.getText());
                switch (operator) {
                    case "+":
                        numd1 = numd1+numd2;
                        break;
                    case "-":
                        numd1 = numd1-numd2;
                        break;
                    case "x":
                        numd1 = numd1*numd2;
                        break;
                    case "/":
                        numd1 = numd1/numd2;
                        break;
                    default:
                        break;
                }
            if (numd1 % 1 == 0){
                sum = (int)numd1;
                String setDisplay = String.valueOf(sum);
                display.setText(setDisplay); 
            }
            else{
                String setDisplay = String.valueOf(numd1);
            display.setText(setDisplay);
            }
            String setDisplay2 = getDisplay + " + ";
            outDisplay2 = outDisplay2+setDisplay2;
            display2.setText(outDisplay2);
            operator ="+";
            }
            
        }
    }//GEN-LAST:event_btnPlusActionPerformed

    private void btnMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinusActionPerformed
        String getDisplay = display.getText();
        if(getDisplay.equals("")){
            display.setText("");
        }
        else if (parameter.equals("0")){
            parameter = "1";
            display.setText("");
            String setDisplay2 = getDisplay + " - ";
            outDisplay2 = outDisplay2+setDisplay2;
            display2.setText(outDisplay2);
            numd1= Double.valueOf(getDisplay);
            operator ="-";
        }
        else if (parameter.equals("1")){
            reset = "y";
            parameter = "2";
            numd2 = Double.valueOf(getDisplay);
            switch (operator) {
                case "+":
                    numd1 = numd1+numd2;
                    break;
                case "-":
                    numd1 = numd1-numd2;
                    break;
                case "x":
                    numd1 = numd1*numd2;
                    break;
                case "/":
                    numd1 = numd1/numd2;
                    break;
                default:
                    break;
            }
            if (numd1 % 1 == 0){
                sum = (int)numd1;
                String setDisplay = String.valueOf(sum);
                display.setText(setDisplay); 
            }
            else{
                String setDisplay = String.valueOf(numd1);
            display.setText(setDisplay);
            }
            String setDisplay2 = getDisplay + " - ";
            outDisplay2 = outDisplay2+setDisplay2;
            display2.setText(outDisplay2);
            operator ="-";
        }
        else if (parameter.equals("2")){
            if(reset.equals("n")){
            reset = "y";
            numd2 = Double.valueOf(display.getText());
                switch (operator) {
                    case "+":
                        numd1 = numd1+numd2;
                        break;
                    case "-":
                        numd1 = numd1-numd2;
                        break;
                    case "x":
                        numd1 = numd1*numd2;
                        break;
                    case "/":
                        numd1 = numd1/numd2;
                        break;
                    default:
                        break;
                }
            if (numd1 % 1 == 0){
                sum = (int)numd1;
                String setDisplay = String.valueOf(sum);
                display.setText(setDisplay); 
            }
            else{
                String setDisplay = String.valueOf(numd1);
            display.setText(setDisplay);
            }
            String setDisplay2 = getDisplay + " - ";
            outDisplay2 = outDisplay2+setDisplay2;
            display2.setText(outDisplay2);
            operator ="-";
            }
            
        }
       
    }//GEN-LAST:event_btnMinusActionPerformed

    private void btnMultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiActionPerformed
       String getDisplay = display.getText();
        if(getDisplay.equals("")){
            display.setText("");
        }
        else if (parameter.equals("0")){
            parameter = "1";
            display.setText("");
            String setDisplay2 = getDisplay + " x ";
            outDisplay2 = outDisplay2+setDisplay2;
            display2.setText(outDisplay2);
            numd1= Double.valueOf(getDisplay);
            operator ="x";
        }
        else if (parameter.equals("1")){
            reset = "y";
            parameter = "2";
            numd2 = Double.valueOf(getDisplay);
           switch (operator) {
               case "+":
                   numd1 = numd1+numd2;
                   break;
               case "-":
                   numd1 = numd1-numd2;
                   break;
               case "x":
                   numd1 = numd1*numd2;
                   break;
               case "/":
                   numd1 = numd1/numd2;
                   break;
               default:
                   break;
           }
            if (numd1 % 1 == 0){
                sum = (int)numd1;
                String setDisplay = String.valueOf(sum);
                display.setText(setDisplay); 
            }
            else{
                String setDisplay = String.valueOf(numd1);
            display.setText(setDisplay);
            }
            String setDisplay2 = getDisplay + " x ";
            outDisplay2 = outDisplay2+setDisplay2;
            display2.setText(outDisplay2);
            operator ="x";
        }
        else if (parameter.equals("2")){
            if(reset.equals("n")){
            reset = "y";
            numd2 = Double.valueOf(display.getText());
                switch (operator) {
                    case "+":
                        numd1 = numd1+numd2;
                        break;
                    case "-":
                        numd1 = numd1-numd2;
                        break;
                    case "x":
                        numd1 = numd1*numd2;
                        break;
                    case "/":
                        numd1 = numd1/numd2;
                        break;
                    default:
                        break;
                }
            if (numd1 % 1 == 0){
                sum = (int)numd1;
                String setDisplay = String.valueOf(sum);
                display.setText(setDisplay); 
            }
            else{
                String setDisplay = String.valueOf(numd1);
            display.setText(setDisplay);
            }
            String setDisplay2 = getDisplay + " x ";
            outDisplay2 = outDisplay2+setDisplay2;
            display2.setText(outDisplay2);
            operator ="x";
            }
            
        }
       
    }//GEN-LAST:event_btnMultiActionPerformed

    private void btnDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivActionPerformed
   String getDisplay = display.getText();
        if(getDisplay.equals("")){
            display.setText("");
        }
        else if (parameter.equals("0")){
            parameter = "1";
            display.setText("");
            String setDisplay2 = getDisplay + " / ";
            outDisplay2 = outDisplay2+setDisplay2;
            display2.setText(outDisplay2);
            numd1= Double.valueOf(getDisplay);
            operator ="/";
        }
        else if (parameter.equals("1")){
            reset = "y";
            parameter = "2";
            numd2 = Double.valueOf(getDisplay);
       switch (operator) {
           case "+":
               numd1 = numd1+numd2;
               break;
           case "-":
               numd1 = numd1-numd2;
               break;
           case "x":
               numd1 = numd1*numd2;
               break;
           case "/":
               numd1 = numd1/numd2;
               break;
           default:
               break;
       }
            if (numd1 % 1 == 0){
                sum = (int)numd1;
                String setDisplay = String.valueOf(sum);
                display.setText(setDisplay); 
            }
            else{
                String setDisplay = String.valueOf(numd1);
            display.setText(setDisplay);
            }
            String setDisplay2 = getDisplay + " / ";
            outDisplay2 = outDisplay2+setDisplay2;
            display2.setText(outDisplay2);
            operator ="/";
        }
        else if (parameter.equals("2")){
            if(reset.equals("n")){
            reset = "y";
            numd2 = Double.valueOf(display.getText());
                switch (operator) {
                    case "+":
                        numd1 = numd1+numd2;
                        break;
                    case "-":
                        numd1 = numd1-numd2;
                        break;
                    case "x":
                        numd1 = numd1*numd2;
                        break;
                    case "/":
                        numd1 = numd1/numd2;
                        break;
                    default:
                        break;
                }
            if (numd1 % 1 == 0){
                sum = (int)numd1;
                String setDisplay = String.valueOf(sum);
                display.setText(setDisplay); 
            }
            else{
                String setDisplay = String.valueOf(numd1);
            display.setText(setDisplay);
            }
            String setDisplay2 = getDisplay + " / ";
            outDisplay2 = outDisplay2+setDisplay2;
            display2.setText(outDisplay2);
            operator ="/";
            }
            
        }
       
    }//GEN-LAST:event_btnDivActionPerformed

    private void btnEqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEqualActionPerformed
        String getDisplay = display.getText();
        if(getDisplay.equals("")){
            display.setText("");
        }
        else if (parameter.equals("0")){
            parameter = "0";
            display.setText(getDisplay);
            String setDisplay2 ="";
            display2.setText(setDisplay2);
            operator ="";
        }
        else if (parameter.equals("1")){
            reset = "y";
            parameter = "0";
            numd2 = Double.valueOf(getDisplay);
            switch (operator) {
                case "+":
                    numd1 = numd1+numd2;
                    break;
                case "-":
                    numd1 = numd1-numd2;
                    break;
                case "x":
                    numd1 = numd1*numd2;
                    break;
                case "/":
                    numd1 = numd1/numd2;
                    break;
                default:
                    break;
            }
            if (numd1 % 1 == 0){
                sum = (int)numd1;
                String setDisplay = String.valueOf(sum);
                display.setText(setDisplay); 
            }
            else{
                String setDisplay = String.valueOf(numd1);
            display.setText(setDisplay);
            }
            outDisplay2 ="";
            display2.setText(outDisplay2);
            operator ="";
        }
        else if (parameter.equals("2")){
            if(reset.equals("n")){
            reset = "y";
            parameter = "0";
            numd2 = Double.valueOf(display.getText());
                switch (operator) {
                    case "+":
                        numd1 = numd1+numd2;
                        break;
                    case "-":
                        numd1 = numd1-numd2;
                        break;
                    case "x":
                        numd1 = numd1*numd2;
                        break;
                    case "/":
                        numd1 = numd1/numd2;
                        break;
                    default:
                        break;
                }
            if (numd1 % 1 == 0){
                sum = (int)numd1;
                String setDisplay = String.valueOf(sum);
                display.setText(setDisplay); 
            }
            else{
                String setDisplay = String.valueOf(numd1);
            display.setText(setDisplay);
            }
            outDisplay2 ="";
            display2.setText(outDisplay2);
            operator ="";
            }
            
        }
    }//GEN-LAST:event_btnEqualActionPerformed

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        String getDisplay = display.getText();
         reset = "n";
        int length = getDisplay.length();
        if(length > 0){
        int del= length - 1;
        display.setText(getDisplay.substring(0,del));
        }
        else{
        display.setText("");
        }
        
        if(operator.equals("")){
            getDisplay = display.getText();
            try{
            numd1=Double.valueOf(getDisplay);}
            catch (NumberFormatException e){
            numd1= 0;
            }
        }
    }//GEN-LAST:event_btnDelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
       //</editor-fold>
       
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Kalkulator().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnDiv;
    private javax.swing.JButton btnDot;
    private javax.swing.JButton btnEqual;
    private javax.swing.JButton btnMin;
    private javax.swing.JButton btnMinus;
    private javax.swing.JButton btnMulti;
    private javax.swing.JButton btnPlus;
    private javax.swing.JTextField display;
    private javax.swing.JLabel display2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
